### ISSUE TITLE
Error in Visual Studio 16.1 trying to open Pending Changes view

### ISSUE THREAD

**Issue by vkirienko** [simonp22/AnkhSVN#3]
Hi, 

I'm getting this error in Visual Studio 16.1 trying to open Pending Changes view.

-----------
System.NullReferenceException: 
Object reference not set to an instance of an object.
   at Ankh.VS.Selection.CommandState.LoadThemeData()
   at Ankh.VS.Selection.CommandState.get_ThemeDefined()
   at Ankh.UI.PendingChanges.Commits.PendingCommitItem.RefreshText(IAnkhServiceProvider context)
   at Ankh.UI.PendingChanges.Commits.PendingCommitItem..ctor(PendingCommitsView view, PendingChange change)
   at Ankh.UI.PendingChanges.Commits.PendingCommitItemCollection.GetWrapItem(PendingChange inner)
   at Ankh.Collections.KeyedWrapNotifyCollection`3.WrapInnerKeyedCollection.ResetCollection()
   at Ankh.Collections.KeyedWrapNotifyCollection`3..ctor(IKeyedNotifyCollection`2 collection, Object context)
   at Ankh.UI.PendingChanges.Commits.PendingCommitsView.Ankh.UI.IPendingChangeUI.set_Items(IKeyedNotifyCollection`2 value)
   at Ankh.UI.PendingChanges.PendingCommitsPage.HookList()
   at Ankh.UI.PendingChanges.PendingCommitsPage.OnLoad(EventArgs e)
   at System.Windows.Forms.UserControl.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at System.Windows.Forms.Control.set_Visible(Boolean value)
   at Ankh.UI.PendingChanges.PendingChangesToolControl.ShowPanel(PendingChangesPage page, Boolean select)
   at Ankh.UI.PendingChanges.PendingChangesToolControl.OnLoad(EventArgs e)
   at System.Windows.Forms.UserControl.OnCreateControl()

**Comment by brz** [comment]
When I restarted Visual Studio it told me it had disabled extensions that were using deprecated APIs. (yellow notification bar on top).
I then opted to enable extensions using the synchronous API and the pending changes window started working correctly again.

**Comment by vkirienko** [comment]
Worked for me. What confused me the fact that check out status in Solution Explorer was showing just fine. Thanks a lot.

**Comment by brettchangus** [comment]
Using 16.1.1. Enabling the synchronous autoload option did not help, the window still showed no content (actually content from whatever tab you clicked on previously) and also broke some of the Resharper functionality (Find Usages).

I was hoping to reinstall to see if that fixed anything but as the extension is no longer available in the marketplace, I wasn't able to try.

**Comment by brz** [comment]
> 
> 
> Using 16.1.0. Enabling the synchronous autoload option did not help, the window still showed no content (actually content from whatever tab you clicked on previously) and also broke some of the Resharper functionality (Find Usages).
> 
> I was hoping to reinstall to see if that fixed anything but as the extension is no longer available in the marketplace, I wasn't able to try.

I'm wondering if this might be a bug in Visual Studio's latest update (16.1.1), rather than AnkhSVN, since ReSharper is also affected...

**Comment by brettchangus** [comment]
It could be a bug with 16.1.1, as that is the version I currently have installed, not 16.1.0 as I previously mentioned.

For whatever reason, disabling AnkhSVN allowed Resharper to work normally with or without the synchronous autoload option enabled. Seems like it was blocking Resharper some how.

**Comment by brettchangus** [comment]
Even after uninstalling AnkhSVN, Resharper > Find Usages randomly stopped working again. Behavior is inconsistent. Seems likely there is a bug in VS 16.1.1.

**Comment by brettchangus** [comment]
Resharper released an update that shows the following warning in VS after updating:
![resharper-warning](https://user-images.githubusercontent.com/29388424/59060035-050f5780-8855-11e9-8fef-1f67acbb1b2f.png)

It mentions that tool windows may not display properly with that "Optimize rendering for screens with different pixel densities" option enabled. Could be the same issue for AnkhSvn > Pending Changes.

**Comment by Liekele** [comment]
I disabled "**Optimize rendering for screens with different pixel densities**" in options and **AnkhSvn > Pending Changes** view worked again for me in **VS 16.1.2**.

Thanks for the tip @brettchangus
